app_name: meli_sales
services:
  - name: backend
    port: 8000
    subdomain: api-meli-sales
    homepage: false
    container: meli_backend
  - name: frontend
    port: 80
    subdomain: meli-sales
    homepage: true
    description: "Meli Sales App"
    icon: mdi-chart-line
    container: meli_frontend